class Autogenerated {
  int? status;
  List<Data>? data;

  Autogenerated({this.status, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }
}

class Data {
  int? id;
  String? question;
  String? typeOfAns;
  dynamic redirectUrl;
  int? status;
  List<Options>? options;

  Data({this.id, this.question, this.typeOfAns, this.redirectUrl, this.status, this.options});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    question = json['question'];
    typeOfAns = json['type_of_ans'];
    redirectUrl = json['redirect_url'];
    status = json['status'];
    if (json['options'] != null) {
      options = <Options>[];
      json['options'].forEach((v) {
        options!.add(Options.fromJson(v));
      });
    }
  }
}

class Options {
  int? id;
  int? questionId;
  String? option;
  dynamic redirectUrl;
  String? nextQuestionId;
  int? status;

  Options({this.id, this.questionId, this.option, this.redirectUrl, this.nextQuestionId, this.status});

  Options.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    questionId = json['question_id'];
    option = json['option'];
    redirectUrl = json['redirect_url'];
    nextQuestionId = json['next_question_id'];
    status = json['status'];
  }
}
