import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;

import '../data/models/q_model.dart';
import '../ui/pages/chat_page.dart';

class ChatController extends GetxController {
  var questions = <Data>[].obs;
  var currentQuestionIndex = 0.obs;
  var isLoading = true.obs;
  var answers = <Map<String, dynamic>>[].obs;

  final String fetchUrl = 'https://api.nexever.org/api/questions-with-answers';
  final String postUrl = 'https://api.nexever.org/api/save-user-answer';
  final Map<String, String> headers = {
    'x-api-key': 'ba6h94mh4-x5h2-70s0-9217-v037v57810e7272fz',
    'Content-Type': 'application/json'
  };

  @override
  void onInit() {
    fetchQuestions();
    super.onInit();
  }

  void fetchQuestions() async {
    try {
      isLoading.value = true;
      final response = await http.get(Uri.parse(fetchUrl), headers: headers);
      if (response.statusCode == 200) {
        final jsonData = json.decode(response.body);
        questions.value = Autogenerated.fromJson(jsonData).data ?? [];
      } else {
        Get.snackbar("Error", "Failed to load questions");
      }
    } catch (e) {
      Get.snackbar("Exception", e.toString());
    } finally {
      isLoading.value = false;
    }
  }

  void selectAnswer(Data question, dynamic answer,
      {String? customAnswer}) async {
    answers.add({
      'question_id': question.id,
      'answer_id': answer is Options ? answer.id : null,
      'custom_answer':
          customAnswer ?? (answer is Options ? answer.option : null),
    });

    if (currentQuestionIndex.value < questions.length - 1) {
      currentQuestionIndex.value++;
    } else {
      await submitAnswers();
    }
  }



  Future<void> submitAnswers() async {
    try {
      for (var answer in answers) {
        final response = await http.post(
          Uri.parse(postUrl),
          headers: headers,
          body: json.encode(answer),
        );

        debugPrint("response:--${response.body}");
        if (response.statusCode != 200) {

          debugPrint("Submission failed for ${answer['question_id']}");
        }
      }
      Get.snackbar("Success", "All answers submitted!");
      showSuccessDialog();
    } catch (e) {
      Get.snackbar("Error", e.toString());
    }
  }
}
